
services:
    nginx:
        image: nginx:latest
        volumes:
        - ./:/var/www
        - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            -   app
        container_name: app_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            -   ./:/var/www
        depends_on:
            - db
        container_name: project_app

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lardocker
            MYSQL_PASSWORD: root
        volumes:
            - ./mysql_data:/var/lib/mysql
        ports:
            - "8101:3306"
        container_name: project_db
